"""Regenerate the one-file Visual Studio edition from the modular sources."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
engine = (root / "src/engine.hpp").read_text(encoding="utf-8").replace("#pragma once\n", "", 1)
main = (root / "src/main.cpp").read_text(encoding="utf-8").replace('#include "engine.hpp"\n', "", 1)
(root / "Backtester.cpp").write_text(
    "// GENERATED by tools/amalgamate.py. Compile this file ALONE as C++17.\n"
    "// No arguments runs SYNTHETIC data, not SPY. See START_HERE.md.\n\n" + engine + "\n" + main,
    encoding="utf-8")
print("Generated Backtester.cpp")
